# Generated by Django 4.2.18 on 2025-01-30 04:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_usersetting"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersetting",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_settings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
